name: Deploy to GCP Cloud Run via Docker Hub

on:
  push:
    branches:
      - main  # Triggers on push to main branch
    paths:
      - 'backEnd/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub (Public)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/techworld-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/techworld-backend:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy techworld-backend \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/techworld-backend:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --port=8000 \
            --env-vars-file=.env